name: solve_tutor
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.2+4

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # nb_utils: ^5.0.8
  intl: ^0.18.1
  google_fonts: ^4.0.0
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_messaging: ^14.6.3
  firebase_analytics: ^10.4.3
  cloud_firestore: ^4.7.1
  image_picker: ^0.8.3+2
  firebase_storage: ^11.2.1
  uuid: ^3.0.4
  google_sign_in: ^6.1.2
  sign_in_with_apple: ^5.0.0
  flutter_keyboard_visibility: ^5.4.1
  shared_preferences: ^2.1.1
  provider: ^6.0.5
  fluttertoast: ^8.2.2

  photo_view: 0.14.0
  cached_network_image: ^3.2.3
  gallery_saver: ^2.3.2
  emoji_picker_flutter: ^1.6.0
  table_calendar: ^3.0.9
  flutter_local_notifications: ^13.0.0
  number_paginator: ^0.2.3

  logging: ^1.2.0
  file_picker: ^5.3.0
  flutter_rating_bar: ^4.0.1
  percent_indicator: ^4.2.3
  dotted_border: ^2.0.0+3
  flutter_reorderable_list: ^1.3.1
  video_thumbnail: ^0.5.3
  flutter_reorderable_grid_view: ^4.0.0
  responsive_framework: ^1.0.0
  flutter_linkify: ^6.0.0
  url_launcher: ^6.1.0
  speech_balloon: ^0.0.4
  video_player: ^2.4.10
  web_socket_channel: ^2.4.0
  videosdk: ^1.1.3
  flutter_dotenv: ^5.1.0
  http: ^0.13.5
  sizer: ^2.0.15
  lottie: ^2.4.0
  flutter_webrtc: ^0.9.34
  camera: ^0.10.5+2
  webview_flutter: ^4.2.2

  flutter_sound: ^9.2.13
  permission_handler: ^10.2.0
  audio_session: ^0.1.6
  path_provider: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSansThai-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansThai-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansThai-Bold.ttf
          weight: 700
    - family: NotoSansMed
      fonts:
        - asset: assets/fonts/NotoSansThai-Medium.ttf
    - family: NotoSansBold
      fonts:
        - asset: assets/fonts/NotoSansThai-Bold.ttf
